version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0.12-node-browsers-legacy
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run:
          name: php test
          command: vendor/bin/phpunit tests/Unit/ShopControllerTest.php